version: '3.8'
services:
  db:
    image: postgres:13
    container_name: sentiment_db
    restart: always
    environment:
      POSTGRES_USER: user             # <-- ¡Corregido!
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentiment_analyzer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: